
on:
  push:
    branches: [ master ]
env:
  ASPNETCORE_ENVIRONMENT: Production
  WEBAPP_PATH: ./
  WEBAPP_CSPROJ: bipinpaul.com.csproj

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: dotnet build
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:  '9.0.x' # SDK Version to use.

      - run: rm  ${{ env.WEBAPP_PATH }}Properties/launchSettings.json
      - run: touch ${{ env.WEBAPP_PATH }}/wwwroot/.nojekyll #folder starting with _ are handled as jekyll. This file will prevent that.  
      - run: dotnet run --project ${{ env.WEBAPP_PATH }}${{env.WEBAPP_CSPROJ}}  --configuration Release
      
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.YOUR_ACCOUNT_ID }}
          projectName: ${{ secrets.YOUR_PROJECT_NAME }}
          directory: ${{ secrets.YOUR_ASSET_DIRECTORY }}
