name: Deploy Site
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.102' # SDK Version to use.
    - run: dotnet run -- deploy
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
       